### ISSUE TITLE
Problème au npm install

### ISSUE THREAD

**Issue by gregorybarale** [NicolasLeRoux/rpaswui#3]
Lors d'un clone du projet, si j'effectue un npm install j'obtiens:
```
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-jp/uFnooOiO+L211eZOoSyzpOITMXx1rBITauYykG3BRYPu8h0UcxsPNB04RR5vo4Tyz3+ay17tR6JVf9qzYWg== integrity checksum failed when using sha512: wanted sha512-jp/uFnooOiO+L211eZOoSyzpOITMXx1rBITauYykG3BRYPu8h0UcxsPNB04RR5vo4Tyz3+ay17tR6JVf9qzYWg== but got sha1-ePrtjD0HSrgfIrTphdeehzj3IPg=. (16426 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-q4spe4KTfsAS1SUHLO0wz8Qiyf1+vMIAgpRYioFYDMNqKfHQbg+AVDH3i4fvpl71/P1L0dBl+fQi+P37UYf0ew== integrity checksum failed when using sha512: wanted sha512-q4spe4KTfsAS1SUHLO0wz8Qiyf1+vMIAgpRYioFYDMNqKfHQbg+AVDH3i4fvpl71/P1L0dBl+fQi+P37UYf0ew== but got sha1-Yi4y6CSItJJ5EUpPns9F581rulU=. (6052 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-PPRybI9+jM5tjtCbN2cxmmRU7YmqT3Zv/UDy48tAh2XRkLa9bAORtSWLkVc13+GJF+cdTh1yEnHEk3cpTaL5Kg== integrity checksum failed when using sha512: wanted sha512-PPRybI9+jM5tjtCbN2cxmmRU7YmqT3Zv/UDy48tAh2XRkLa9bAORtSWLkVc13+GJF+cdTh1yEnHEk3cpTaL5Kg== but got sha1-4dvAOpudO6B+iWrQJzF+tnmhCh8=. (6260 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ== integrity checksum failed when using sha512: wanted sha512-MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ== but got sha1-wZyd+aAocC1nhhI4SmVSQExjbRU=. (15621 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-lreewLK/BlghmxtfH36YYVg1i8IAce4TI7oao75I1g245+6BctqTVQiBP3YUJ9C6DQOXJmkYR9X9fCLtCOJc5w== integrity checksum failed when using sha512: wanted sha512-lreewLK/BlghmxtfH36YYVg1i8IAce4TI7oao75I1g245+6BctqTVQiBP3YUJ9C6DQOXJmkYR9X9fCLtCOJc5w== but got sha1-LtgVDSShbqhlHm1u8PR8QVjOejY=. (5535 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-Y9J6ZjXtoYh8RnXVCMOU/ttDmk1aBjunq9vO0ta5x85WDQiQfUF9sIPBITdbiiIVcBo03Hi3jMxigBtsddlXRw== integrity checksum failed when using sha512: wanted sha512-Y9J6ZjXtoYh8RnXVCMOU/ttDmk1aBjunq9vO0ta5x85WDQiQfUF9sIPBITdbiiIVcBo03Hi3jMxigBtsddlXRw== but got sha1-aALmJk79GMeQobDVF/DyYnvyyUo=. (3526 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARNWARN  registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-xcJpopdamTuY5duC/KnTTNBraPK54YwpenP4lzxU8H91GudWpFv38u0CKjclE1Wi2EH2EDz5LRcHcKbCIzqGyg== integrity checksum failed when using sha512: wanted sha512-xcJpopdamTuY5duC/KnTTNBraPK54YwpenP4lzxU8H91GudWpFv38u0CKjclE1Wi2EH2EDz5LRcHcKbCIzqGyg== but got sha1-/wS9/AEO5UfXgL7DjhrBwnd9JTo=. (4209 bytes)
registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-ijDLlyQ7s6x1JgCLur53osjm/UXUYD9+0PbYKrBsYisYXzCxN+HC3mYDNy/dWdmf3AwqwU3CXwDCvsNgGK1S0w== integrity checksum failed when using sha512: wanted sha512-ijDLlyQ7s6x1JgCLur53osjm/UXUYD9+0PbYKrBsYisYXzCxN+HC3mYDNy/dWdmf3AwqwU3CXwDCvsNgGK1S0w== but got sha1-Vx4PGwYEY268DfwhsDObvjE0FxA=. (2069 bytes)
WARNWARN  registryregistry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
 Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> opencv@6.0.0 install /Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@8.9.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@8.9.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv/build'
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64/opencv.node" "--module_name=opencv" "--module_path=/Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64"
gyp ERR! cwd /Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 17.3.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv
node-pre-gyp ERR! node -v v8.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64' (1)
gyp ERR! configure error stall: info lifecycle opencv@6.0.0~install: Failed to exec install script
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv/build'
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64/opencv.node" "--module_name=opencv" "--module_path=/Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv/build/opencv/v6.0.0/Release/node-v57-darwin-x64"
gyp ERR! cwd /Users/gregorybarale/Development/perso/challenge_innovation/rpaswui/node_modules/opencv
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@6.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gregorybarale/.npm/_logs/2018-01-03T21_14_37_695Z-debug.log
```

J'imagine qu'il faut installer autre chose avant?

**Comment by NicolasLeRoux** [comment]
@gregorybarale En effet, il y a plusieurs install à faire avant. Mais j'ai commencer le split du code en 2 projets:
- __rpaswui__ pour le client web
- __rpas__ pour le code embarqué sur le drone

Du coup, j'ai pas mal de dépendance à déplacer d'un projet vers l'autre.

Sinon, le problème que tu rencontres vient de la nécessité d'installer python (en autre). Je fais la MàJ du README dès que j'ai déplacé les deps.

**Comment by NicolasLeRoux** [comment]
C'est bon, j'ai supprimer tout le code qui ne va pas dans ce projet, il ne reste plus grand chose...
